name: Keep Codespace Alive for 24*7 by @DARKESPYT

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-codespace:
    runs-on: ubuntu-latest

    steps:
    - name: Action Checkout code by @DARKESPYT
      uses: actions/checkout@v3

    - name: Install Required Packages and Libraries by @DARKESPYT
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install pexpect

    - name: LOGIN INTO GH CLI by @DARKESPYT
      run: |
        echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
        gh auth status

    - name: Starting Codespace by @DARKESPYT
      env:
        CODESPACE: fuzzy-space-palm-tree-5gq5jvwqjxrrfj6j
      run: |
        STATUS=$(gh codespace list --json name,state --jq '.[] | select(.name == "${{ env.CODESPACE }}") | .state')
        if [ "$STATUS" == "Shutdown" ]; then
          gh codespace ssh --codespace $CODESPACE
        fi
        while true; do
          STATUS=$(gh codespace list --json name,state --jq '.[] | select(.name == "${{ env.CODESPACE }}") | .state')
          if [ "$STATUS" == "Available" ]; then
            break
          fi
        done

    - name: Run Bot Script in Codespace by @DARKESPYT
      env:
        CODESPACE: fuzzy-space-palm-tree-5gq5jvwqjxrrfj6j
        SCRIPT_PATH: /workspaces/src-forwarder/start.py
        PHONE_NUMBER: +918678996799
      run: |
        echo "import pexpect

codespace = '${{ env.CODESPACE }}'
phone_number = '${{ env.PHONE_NUMBER }}'
script_path = '${{ env.SCRIPT_PATH }}'

def run_script():
    session = pexpect.spawn(f'gh codespace ssh -c {codespace}')
    session.expect(['$', '#'])
    session.sendline(f'tmux new-session -d -s bot "rm -rf *.zip && rm -rf extracted* && python3 {script_path}"')
    session.expect(['$', '#'])
    session.sendline(f'tmux send-keys -t bot \"python3 {script_path}\" C-m')
    session.expect(\"Please enter your phone (or bot token): \")
    session.sendline(f\"{phone_number}\")
    session.interact()

if __name__ == '__main__':
    run_script()
" > run_bot.py
        python3 run_bot.py
        
