name: Keep Codespace Alive for 24*7 by @DARKESPYT

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'

jobs:
  run-codespace:
    runs-on: ubuntu-latest

    steps:
    - name: Action Checkout code by @DARKESPYT
      uses: actions/checkout@v3

    - name: Install Required Packages and Libraries by @DARKESPYT
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y python3-full

    - name: LOGIN INTO GH CLI by @DARKESPYT
      run: |
        echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
        gh auth status

    - name: Starting Codespace by @DARKESPYT
      env:
        CODESPACE: fuzzy-space-palm-tree-5gq5jvwqjxrrfj6j
      run: |
        STATUS=$(gh codespace list --json name,state --jq '.[] | select(.name == "${{ env.CODESPACE }}") | .state')
        if [ "$STATUS" == "Shutdown" ]; then
          gh codespace ssh --codespace $CODESPACE
        fi
        while true; do
          STATUS=$(gh codespace list --json name,state --jq '.[] | select(.name == "${{ env.CODESPACE }}") | .state')
          if [ "$STATUS" == "Available" ]; then
            break
          fi
        done
      
    - name: Run Bot Script in Codespace by @DARKESPYT
      env:
        CODESPACE: fuzzy-space-palm-tree-5gq5jvwqjxrrfj6j
        SCRIPT_PATH: /workspaces/src-forwarder/start.py
        PHONE_NUMBER: +918678996799
        OTP_CODE: ${{ secrets.OTP }}
      run: |
        check_codespace() {
          STATUS=$(gh codespace list --json name,state --jq '.[] | select(.name == "'"${CODESPACE}"'") | .state')
          echo "$STATUS"
        }
        while true; do
          STATUS=$(check_codespace)
          if [ "$STATUS" == "Available" ]; then
            echo "Codespace is available. Starting the bot script."
            break
          fi
          echo "Codespace is not available yet. Checking again..."
        done
        while true; do
          gh codespace ssh -c "${CODESPACE}" -- bash -c "
            rm -rf *.zip
            rm -rf extracted*
            python3 ${SCRIPT_PATH} <<EOF
          ${PHONE_NUMBER}
          ${OTP_CODE}
          EOF"
        done
  
