name: Keep Codespace Alive for 24*7 by @DARKESPYT

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-codespace:
    runs-on: ubuntu-latest

    steps:
    - name: Action Checkout code by @DARKESPYT
      uses: actions/checkout@v3

    - name: Install Required Packages and Libraries by @DARKESPYT
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip
        pip3 install pexpect

    - name: LOGIN INTO GH CLI by @DARKESPYT
      run: |
        echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
        gh auth status

    - name: Starting Codespace by @DARKESPYT
      env:
        CODESPACE: fuzzy-space-palm-tree-5gq5jvwqjxrrfj6j
      run: |
        STATUS=$(gh codespace list --json name,state --jq '.[] | select(.name == "${{ env.CODESPACE }}") | .state')
        if [ "$STATUS" == "Shutdown" ]; then
          gh codespace ssh --codespace $CODESPACE
        fi
        while true; do
          STATUS=$(gh codespace list --json name,state --jq '.[] | select(.name == "${{ env.CODESPACE }}") | .state')
          if [ "$STATUS" == "Available" ]; then
            break
          fi
        done
        
    - name: Use Telegram Session File by @DARKESPYT
      run: |
        chmod 600 /workspaces/src-forwarder/${{ secrets.SESSION_FILE }}.session
      
    - name: Run Bot Script in Codespace by @DARKESPYT
      env:
        CODESPACE: fuzzy-space-palm-tree-5gq5jvwqjxrrfj6j
        SCRIPT_PATH: /workspaces/src-forwarder/start.py
        PHONE_NUMBER: +918678996799
        SESSION_FILE: $GITHUB_WORKSPACE/${{ secrets.SESSION_FILE }}.session
      run: |
        gh codespace ssh -c "${CODESPACE}" -- tmux new-session -d -s bot "rm -rf *.zip && rm -rf extracted* && echo ${PHONE_NUMBER} | python3 ${SCRIPT_PATH}"
        
