name: Keep Codespace Alive for 24*7 by @DARKESPYT

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-codespace:
    runs-on: ubuntu-latest

    steps:
    - name: Action Checkout code by @DARKESPYT
      uses: actions/checkout@v3

    - name: Install Required Packages and Libraries by @DARKESPYT
      run: |
        sudo apt install python3-full expect

    - name: LOGIN INTO GH CLI by @DARKESPYT
      run: |
        echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token
        gh auth status

    - name: Adding SSH Access by @DARKESPYT
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GH_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git remote set-url origin git@github.com:tg-darkespyt/src-forwarder.git

    - name: Starting Codespace by @DARKESPYT
      env:
        CODESPACE: fuzzy-space-palm-tree-5gq5jvwqjxrrfj6j
      run: |
        STATUS=$(gh codespace list --json name,state --jq '.[] | select(.name == "${{ env.CODESPACE }}") | .state')
        if [ "$STATUS" == "Shutdown" ]; then
          gh codespace ssh --codespace $CODESPACE
        fi
        while true; do
          STATUS=$(gh codespace list --json name,state --jq '.[] | select(.name == "${{ env.CODESPACE }}") | .state')
          if [ "$STATUS" == "Available" ]; then
            break
          fi
        done
      
    - name: Run Bot Script in Codespace by @DARKESPYT
      env:
        CODESPACE: fuzzy-space-palm-tree-5gq5jvwqjxrrfj6j
        SCRIPT_PATH: start.py
        PHONE_NUMBER: +918678996799
        OTP_CODE: ${{ secrets.OTP }}
      run: |
        gh codespace ssh --codespace "${CODESPACE}"
        tmux new-session -d -s bot 'git pull origin main && pip3 install telethon pyzipper && python3 ${SCRIPT_PATH}'
        echo "Bot Started"
        while true; do
          git config --global user.name "tg-darkespyt"
          git config --global user.email "darkespyt8577@gmail.com"
          if [ -f passwords.db ]; then
            git add .
            if ! git diff --cached --quiet; then
              git commit -m "Automated backup of passwords.db."
              git push origin main
              echo "Bot Database Backed up, check the repository."
            else
              echo "No changes to commit."
            fi
          else
            echo "Failed to take backup of the Bot Database."
          fi
          sleep 60
        done